### ISSUE TITLE
sphere in a uniform magnetostatic field

### ISSUE THREAD

**Issue by lheagy** [simpeg/geoana#36]
In `geoana/geoana/em/static/sphere.py` we should also include the solution for a permeable sphere in a uniform magnetostatic field. The solution for the magnetic field is in Ward and Hohmann (6.69). The derivation follows the conducting sphere in a uniform electrostatic field. 

![image](https://user-images.githubusercontent.com/6361812/166488374-293f02f1-88be-4601-bfe8-2b8a624b329e.png)

The implementation should include methods to compute:
- potential 
- secondary magnetic field (Hs)
- total magnetic field
- secondary magnetic flux 
- total magnetic flux

**Comment by jcapriot** [comment]
In my opinion there's a lot of redundant functions in that spatial module that are handled with simple operations...
i.e. just call `xyz - self.location` instead of defining a function to just subtract two things...
when calling for the distance, just use `np.linalg.norm`. My point is, there are already plenty of functions that already do these operations, and it's needless to wrap them.

**Comment by lheagy** [comment]
Part of where I do find the simple things in `spatial` useful is that they take care of shapes and such (e.g. `xyz - self.location` won't work because xyz can be a 2D array of shape `(nD, 3)`)  so `spatial.vector_distance` takes care of that https://github.com/simpeg/geoana/blob/6fb20060388d91d982be10f000d1e14bbf6c9c00/geoana/spatial.py#L411

I realize it is a simple calculation, but is used all over the place and lets us consolidate validation to one place. I don't feel super-strongly about this, but I see places where it can simplify our lives a bit
